package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"sre-triage-agent/internal/tools"

	"google.golang.org/genai"
)

type Config struct {
	Model     string
	ProjectID string
	Location  string
	APIKey    string
	Client    *genai.Client
}

type ToolDispatcher func(name string, args map[string]any) (any, error)

type Agent struct {
	client     *genai.Client
	ModelName  string
	dispatcher ToolDispatcher
}

func NewAgent(ctx context.Context, cfg Config) (*Agent, error) {
	if cfg.Model == "" {
		cfg.Model = os.Getenv("GEMINI_MODEL")
		if cfg.Model == "" {
			cfg.Model = "gemini-3.8-flash"
		}
	}

	if cfg.Client != nil {
		return &Agent{
			client:     cfg.Client,
			ModelName:  cfg.Model,
			dispatcher: tools.DispatchTool,
		}, nil
	}

	clientCfg := &genai.ClientConfig{}

	// Check if Vertex AI should be used
	project := cfg.ProjectID
	if project == "" {
		project = os.Getenv("GOOGLE_CLOUD_PROJECT")
	}
	location := cfg.Location
	if location == "" {
		location = os.Getenv("GOOGLE_CLOUD_LOCATION")
		if location == "" {
			location = "global"
		}
	}

	apiKey := cfg.APIKey
	if apiKey == "" {
		apiKey = os.Getenv("GEMINI_API_KEY")
	}

	if project != "" || os.Getenv("GOOGLE_GENAI_USE_VERTEXAI") == "true" {
		clientCfg.Backend = genai.BackendVertexAI
		clientCfg.Project = project
		clientCfg.Location = location
		log.Printf("Agent using Vertex AI Backend (project=%s, location=%s)", project, location)
	} else if apiKey != "" {
		clientCfg.Backend = genai.BackendGeminiAPI
		clientCfg.APIKey = apiKey
		log.Println("Agent using Gemini API Backend via API Key")
	} else {
		// Default to Vertex AI with ADC
		clientCfg.Backend = genai.BackendVertexAI
		clientCfg.Location = location
		log.Println("Agent defaulting to Vertex AI Backend with Application Default Credentials")
	}

	client, err := genai.NewClient(ctx, clientCfg)
	if err != nil {
		return nil, fmt.Errorf("failed to create genai client: %w", err)
	}

	return &Agent{
		client:     client,
		ModelName:  cfg.Model,
		dispatcher: tools.DispatchTool,
	}, nil
}

func NewAgentWithDispatcher(cfg Config, dispatcher ToolDispatcher) (*Agent, error) {
	if cfg.Model == "" {
		cfg.Model = "gemini-3.8-flash"
	}
	return &Agent{
		client:     cfg.Client,
		ModelName:  cfg.Model,
		dispatcher: dispatcher,
	}, nil
}

func (a *Agent) Invoke(ctx context.Context, userPrompt string, contextID string) (string, error) {
	if a.client == nil {
		return "Agent client is uninitialized. Ensure credentials (ADC or GEMINI_API_KEY) are configured.", nil
	}

	systemContent := &genai.Content{
		Role: "system",
		Parts: []*genai.Part{
			{Text: GetSystemInstruction()},
		},
	}

	history := []*genai.Content{
		{
			Role: "user",
			Parts: []*genai.Part{
				{Text: userPrompt},
			},
		},
	}

	toolDefs := tools.GetToolDeclarations()
	maxTurns := 8

	for turn := 0; turn < maxTurns; turn++ {
		genCfg := &genai.GenerateContentConfig{
			SystemInstruction: systemContent,
			Tools:             toolDefs,
		}

		resp, err := a.client.Models.GenerateContent(ctx, a.ModelName, history, genCfg)
		if err != nil {
			return "", fmt.Errorf("gemini generate content error: %w", err)
		}

		if len(resp.Candidates) == 0 || resp.Candidates[0].Content == nil {
			return "No response generated by model.", nil
		}

		candidate := resp.Candidates[0]
		history = append(history, candidate.Content)

		var functionCalls []*genai.FunctionCall
		for _, part := range candidate.Content.Parts {
			if part.FunctionCall != nil {
				functionCalls = append(functionCalls, part.FunctionCall)
			}
		}

		// If no tools were called, return the text content
		if len(functionCalls) == 0 {
			var textOutput string
			for _, part := range candidate.Content.Parts {
				if part.Text != "" {
					textOutput += part.Text
				}
			}
			return textOutput, nil
		}

		// Execute function calls
		var responseParts []*genai.Part
		for _, fc := range functionCalls {
			result, err := a.dispatcher(fc.Name, fc.Args)
			if err != nil {
				result = map[string]string{"error": err.Error()}
			}
			resultMap, ok := result.(map[string]any)
			if !ok {
				b, marshalErr := json.Marshal(result)
				if marshalErr == nil {
					var m map[string]any
					if unmarshalErr := json.Unmarshal(b, &m); unmarshalErr == nil {
						resultMap = m
						ok = true
					}
				}
				if !ok {
					resultMap = map[string]any{"output": result}
				}
			}

			responseParts = append(responseParts, &genai.Part{
				FunctionResponse: &genai.FunctionResponse{
					Name:     fc.Name,
					Response: resultMap,
				},
			})
		}

		history = append(history, &genai.Content{
			Role:  "tool",
			Parts: responseParts,
		})
	}

	return "Reached maximum triage loop iterations.", nil
}
